import { useEffect, useState } from 'react';
import { adminApi, eventApi } from '@/api';
import type { EventResponse } from '@/types/event';
import type { FlightResponse } from '@/types/resource';
import Button from '@/components/ui/Button';
import ImportDropzone from '@/components/admin/ImportDropzone';

export default function FlightsPage() {
  const [events, setEvents] = useState<EventResponse[]>([]); const [eventId, setEventId] = useState(''); const [flights, setFlights] = useState<FlightResponse[]>([]); const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState<unknown>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const load = async (id: string) => { if (!id) return setFlights([]); setFlights(await adminApi.listFlights({ event_id: id })); };
  useEffect(() => { void eventApi.listEvents().then((items) => { setEvents(items); if (items[0]) { setEventId(items[0].id); void load(items[0].id); } }); }, []);
  async function importFlights() { if (!file || !eventId) return; setLoading(true); setMessage(''); try { setResult(await adminApi.importFlights(file, eventId)); setFile(null); await load(eventId); } catch { setMessage('Import thất bại. Kiểm tra file và Event.'); } finally { setLoading(false); } }
  async function downloadTemplate() { const blob = await adminApi.downloadFlightTemplate(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'flight_import_template.xlsx'; anchor.click(); URL.revokeObjectURL(url); }
  return <div className="page-container space-y-6"><header><h1 className="text-2xl font-bold">Quản lý chuyến bay</h1><p className="mt-1 text-sm text-slate-500">Import và kiểm tra chuyến bay theo từng Event.</p></header><section className="card p-4"><label className="form-label">Event</label><select className="input" value={eventId} onChange={(e) => { setEventId(e.target.value); void load(e.target.value); }}><option value="">Chọn Event</option>{events.map((event) => <option key={event.id} value={event.id}>{event.event_name}</option>)}</select></section><section className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Import chuyến bay từ Excel</h2><p className="mt-1 text-sm text-slate-500">Chỉ import vào Event đang chọn.</p></div><Button variant="secondary" onClick={() => void downloadTemplate()}>Tải template</Button></div><div className="mt-4"><ImportDropzone onFile={setFile} /></div>{file && <p className="mt-3 text-sm">File: <strong>{file.name}</strong></p>}<Button className="mt-4" disabled={!eventId || !file || loading} onClick={() => void importFlights()}>{loading ? 'Đang import...' : 'Import chuyến bay'}</Button>{message && <p className="mt-3 text-sm text-red-600">{message}</p>}{result !== null && <pre className="mt-4 overflow-x-auto rounded bg-slate-900 p-3 text-xs text-white">{JSON.stringify(result, null, 2)}</pre>}</section><section className="card p-6"><h2 className="font-semibold">Danh sách chuyến bay ({flights.length})</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b"><th className="px-3 py-2">Mã</th><th className="px-3 py-2">Hướng</th><th className="px-3 py-2">Lộ trình</th><th className="px-3 py-2">Khởi hành</th><th className="px-3 py-2">Đã xếp/Slot</th></tr></thead><tbody>{flights.map((flight) => <tr className="border-b" key={flight.id}><td className="px-3 py-2 font-semibold">{flight.flight_code}</td><td className="px-3 py-2">{flight.direction}</td><td className="px-3 py-2">{flight.origin} → {flight.destination}</td><td className="px-3 py-2">{new Date(flight.departure_time).toLocaleString('vi-VN')}</td><td className="px-3 py-2">{flight.assigned_count}/{flight.total_slots}</td></tr>)}</tbody></table></div></section></div>;
}